/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seproject;

import java.sql.SQLException;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Adhiraj
 */
public class Application extends javax.swing.JFrame {

    Home home = null;
    String name = null;
    MySQLAccess msa = new MySQLAccess();
    JPanel message = new JPanel();
    String uid;
    String what;

    /**
     * Creates new form VisaApplication
     */
    public Application() {
        initComponents();
        getAllCountries();
    }

    public Application(Home home, String userID, String what) {
        try {
            message.setLayout(new BoxLayout(message, BoxLayout.Y_AXIS));
            this.home = home;
            initComponents();
            uid = userID;
            this.what = what;
            userIDField.setText(userID);
            msa.loadDatabase();
            msa.preparedStatement = msa.connect.prepareStatement("select name from user where userID = ?");
            msa.preparedStatement.setString(1, this.uid);
            msa.resultSet = msa.preparedStatement.executeQuery();
            if (msa.resultSet.next() == false) {
                message.add(new JLabel("No records found"));
                JOptionPane.showConfirmDialog(this, message, "Invalid", JOptionPane.OK_CANCEL_OPTION);
            }
            name = msa.resultSet.getString(1);
            nameField.setText(name);
            getAllCountries();
        } catch (SQLException ex) {
            Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            ex.printStackTrace();
        } catch (Exception ex) {
            Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
        }
        switch (what) {
            case "visa":
                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Visa Application"));
                break;
            case "export":
                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Export Application"));
                break;
        }
    }

    // Populates the CountryComboBox with all countries
    private void getAllCountries() {
        String[] countries = new String[Locale.getISOCountries().length];
        String[] countryCodes = Locale.getISOCountries();
        for (int i = 0; i < countryCodes.length; i++) {
            Locale obj = new Locale("", countryCodes[i]);
            countries[i] = obj.getDisplayCountry();
            countryComboBox.addItem(countries[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userIDField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        countryComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        purposeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        startDatePicker = new org.jdesktop.swingx.JXDatePicker();
        endDatePicker = new org.jdesktop.swingx.JXDatePicker();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 542));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Visa Application"));

        jLabel1.setText("User ID:");

        jLabel2.setText("Name:");

        jLabel7.setText("Destination:");

        jLabel8.setText("Purpose:");

        userIDField.setEditable(false);
        userIDField.setColumns(15);
        userIDField.setToolTipText("Auto generated");

        nameField.setEditable(false);
        nameField.setColumns(15);
        nameField.setToolTipText("Enter your name");

        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        countryComboBox.setToolTipText("Select nationality");

        submitButton.setText("Submit");
        submitButton.setToolTipText("Submit application");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.setToolTipText("Clear all fields");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Start date:");

        jLabel4.setText("End date:");

        startDatePicker.setToolTipText("Pick first date of visit");

        endDatePicker.setToolTipText("Pick last date of visit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(nameField)
                    .addComponent(countryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purposeTextField)
                    .addComponent(startDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(purposeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton.setText("Back");
        backButton.setToolTipText("Go back to the previous screen");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        if (home != null) {
            home.setVisible(true);
            this.setVisible(false);
        } else {
            JPanel exit = new JPanel();
            exit.setLayout(new BoxLayout(exit, BoxLayout.Y_AXIS));
            exit.add(new JLabel("Nothing to go back to, exiting instead."));
            int result = JOptionPane.showConfirmDialog(this, exit, "Exit?", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        userIDField.setText(this.uid);
        nameField.setText(name);
        countryComboBox.setSelectedIndex(0);
        purposeTextField.setText("");
        startDatePicker.setDate(null);
        endDatePicker.setDate(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            // TODO add your handling code here:
            message.setLayout(new BoxLayout(message, BoxLayout.Y_AXIS));
            if (userIDField.getText().equals("") || nameField.getText().equals("") || countryComboBox.getSelectedItem() == null || purposeTextField.getText().equals("") || startDatePicker.getDate() == null || endDatePicker.getDate() == null) {
                message.add(new JLabel("Some fields are empty."));
                JOptionPane.showConfirmDialog(this, message, "Confirm Details", JOptionPane.OK_CANCEL_OPTION);
            }
            String type = null;
            String db = null;
            switch (what) {
                case "visa":
                    type = "Visa";
                    db = "visaforms";
                    break;
                case "export":
                    type = "Export";
                    db = "exports";
                    break;
            }
            String country = countryComboBox.getItemAt(countryComboBox.getSelectedIndex());
            String purpose = purposeTextField.getText();
            Date startDate = startDatePicker.getDate();
            Date endDate = endDatePicker.getDate();
            java.util.Date date = startDatePicker.getDate();
            java.sql.Date insertStartDate = new java.sql.Date(date.getTime());
            date = endDatePicker.getDate();
            java.sql.Date insertEndDate = new java.sql.Date(date.getTime());
            msa.preparedStatement = msa.connect.prepareStatement("select * from visaforms where userID = ? and (startDate in (?,?)) or (endDate in (?,?))");
            msa.preparedStatement.setString(1, this.uid);
            msa.preparedStatement.setDate(2, insertStartDate);
            msa.preparedStatement.setDate(3, insertEndDate);
            msa.preparedStatement.setDate(4, insertStartDate);
            msa.preparedStatement.setDate(5, insertStartDate);
            msa.resultSet = msa.preparedStatement.executeQuery();
            if (msa.resultSet.first() == true) {
                message.add(new JLabel(type + " has already been issued for this time period."));
                JOptionPane.showConfirmDialog(this, message, "Re-enter dates", JOptionPane.OK_CANCEL_OPTION);
                resetButton.doClick();
            }
            if (startDate.compareTo(endDate) >= 0) {
                message.add(new JLabel(type + " cannot be issued for this time period."));
                JOptionPane.showConfirmDialog(this, message, "Re-enter dates", JOptionPane.OK_CANCEL_OPTION);
                resetButton.doClick();
            } else {
                msa.loadDatabase();
                msa.preparedStatement = msa.connect.prepareStatement("insert into " + db + " values(?, ?, ?, ?, ?, ?, ?)");
                msa.preparedStatement.setString(1, this.uid);
                msa.preparedStatement.setString(2, nameField.getText());
                msa.preparedStatement.setString(3, purpose);
                msa.preparedStatement.setString(4, country);
                msa.preparedStatement.setDate(5, insertStartDate);
                msa.preparedStatement.setDate(6, insertEndDate);
                msa.preparedStatement.setString(7, "Pending");
                msa.resultSet = msa.preparedStatement.executeQuery();
                message.add(new JLabel("Your " + type + " application has been sent to a government official"));
                JOptionPane.showConfirmDialog(this, message, "Success", JOptionPane.OK_CANCEL_OPTION);
            }
            msa.close();
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> countryComboBox;
    private org.jdesktop.swingx.JXDatePicker endDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField purposeTextField;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JButton resetButton;
    private org.jdesktop.swingx.JXDatePicker startDatePicker;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField userIDField;
    // End of variables declaration//GEN-END:variables
}
